#
#Oracle Java 8 Dockerfile
#
# https://github.com/dockerfile/java
# https://github.com/dockerfile/java/tree/master/oracle-java8
# build:  open terminal in directory with this dockerfile. enter: docker build -t YOURNAME . ( . i important)
# run: docker run -d  -p 8048:8048 -p 8080:8080 -p 8081:8081   -p 8148:8148 -p 8180:8180 -p 8181:8181   -p 8248:8248 -p 8280:8280 -p 8281:8281   -p 8348:8348 -p 8380:8380 -p 8381:8381   -p 8448:8448 -p 8480:8480 -p 8481:8481 YOURNAME



FROM ubuntu:16.04

MAINTAINER Niko Benkler

#install software property managemnet
RUN apt-get update && \
    apt-get install -y software-properties-common python-software-properties unzip yum ant sed vim netcat-openbsd

# Install Java.
RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    add-apt-repository -y ppa:webupd8team/java && \
    apt-get update && \
    apt-get install -y oracle-java8-installer && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/cache/oracle-jdk8-installer

# Set environment variables
ENV MD5=4e7ce65489347960e9797d2161e0ada2 \
    JAVA_HOME=/usr/lib/jvm/java-8-oracle \
    PASSWORD=password

   
# update aptitude
RUN apt-get update

#Install git
RUN apt-get install -y git python-virtualenv

#clone git project from url
RUN git clone https://github.com/cocome-community-case-study/cocome-cloud-jee-docker.git usr/src/

#path set so startdomain.sh is less complicatet #not possible -> passwordfile has to be created
#ENV PATH /usr/src/glassfish/glassfish4/glassfish/bin:$PATH

ADD startdomain.sh /startdomain.sh 
ADD stopdomain.sh /stopdomain.sh   
RUN chmod +x /*.sh



ADD web8048.war /usr/src/ 
ADD store8148.ear /usr/src/ 
ADD adapter8248.ear /usr/src/ 
ADD enterprise8348.ear /usr/src/ 
ADD registry8448.war /usr/src/ 


RUN rm usr/src/*.md  && \
	rm -r usr/src/docker && \
	rm usr/src/glassfish/README.md

# 4848 (administration), 8080 (HTTP listener), 8181 (HTTPS listener)
EXPOSE 8048 8080 8081 8148 8180 8181 8248 8280 8281 8348 8380 8381 8448 8480 8481

CMD ["/startdomain.sh"]


